[package]
name = "ide"
version = "0.0.0"
edition = "2021"

[dependencies]
salsa = "0.17.0-pre.1"
tracing = "0.1.29"

base_db = { path = "../base_db" }
hir_def = { path = "../hir_def" }
hir_ty = { path = "../hir_ty" }
hir = { path = "../hir" }
ide_completion = { path = "../ide_completion" }
syntax = { path = "../syntax" }
wgsl_formatter = { path = "../wgsl_formatter" }
rowan = "0.15"
lsp-types = "0.93.0"
vfs = { git = "https://github.com/rust-analyzer/rust-analyzer", rev = "62649a5" }

expect-test = "1.1.0"
itertools = "0.10.1"
smol_str = "0.1.21"

naga11 = { package = "naga", version = "0.11", features = [
  "wgsl-in",
  "validate",
  "span",
] }
naga12 = { package = "naga", version = "0.12", features = [
  "wgsl-in",
  "validate",
  "span",
] }
naga13 = { package = "naga", version = "0.13", features = [
  "wgsl-in",
  "validate",
  "span",
] }
naga14 = { package = "naga", version = "0.14", features = [
  "wgsl-in",
  "validate",
  "span",
] }
naga19 = { package = "naga", version = "0.19", features = [ "wgsl-in" ] }
naga22 = { package = "naga", version = "22", features = [ "wgsl-in" ] }
nagamain = { package = "naga", git = "https://github.com/gfx-rs/wgpu", rev = "765c20235ea712fd14ad1b9e36bbb2071a86e319", features = [ "wgsl-in" ] }
